// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCk2CtmxgQSaaYdQLAGQn7ltC9ws_IyeE',
    appId: '1:921107940303:web:8b8de8402cfcbf3a2d08ba',
    messagingSenderId: '921107940303',
    projectId: 'chatappdemo-41c38',
    authDomain: 'chatappdemo-41c38.firebaseapp.com',
    storageBucket: 'chatappdemo-41c38.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8jx2f3elT15kS6aHCoeHrPWRG6QWY-qY',
    appId: '1:921107940303:android:7d8d7ac678c290dd2d08ba',
    messagingSenderId: '921107940303',
    projectId: 'chatappdemo-41c38',
    storageBucket: 'chatappdemo-41c38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM92y7xo0BanSDfqvGkKga62VEiXlgaa0',
    appId: '1:921107940303:ios:aa9819a446dcd2bb2d08ba',
    messagingSenderId: '921107940303',
    projectId: 'chatappdemo-41c38',
    storageBucket: 'chatappdemo-41c38.appspot.com',
    iosBundleId: 'com.example.flutterChatDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM92y7xo0BanSDfqvGkKga62VEiXlgaa0',
    appId: '1:921107940303:ios:a1534ec6bd8c0a592d08ba',
    messagingSenderId: '921107940303',
    projectId: 'chatappdemo-41c38',
    storageBucket: 'chatappdemo-41c38.appspot.com',
    iosBundleId: 'com.example.flutterChatDemo.RunnerTests',
  );
}
